spring:
  application:
    name: loginservice

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka_uri:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

microservices:
  databaseService:
    fetchUser: http://databaseservice//user?username=%s
