spring:
  application:
    name: loginservice

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka_uri:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

microservices:
  databaseservice:
    authentication: http://databaseservice//domain/user/authentication?username=%s
